title: "Moj ZET App Guide (QR & NFC)"
description: "a practical guide for advanced use of the Moj ZET App"

# Remote theme setup
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme

# Mermaid plugin support
mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "9.1.3"

# Just the Docs configuration
just_the_docs:
  # Collapses child pages under their parent in the sidebar
  collapse_section_nav: true
  nav:
    - "English Guide": "index.md"
    - "Croatian Guide": "index_hr.md"
nav_enabled: true

search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  rel_url: true
  button: false

heading_anchors: true

nav_external_links:
 - title: ZET App Guide on GitHub
   url: https://github.com/fscek/moj-zet-app-guide
   hide_icon: false # set to true to hide the external link icon - defaults to false
   opens_in_new_tab: true # set to true to open this link in a new tab - defaults to false

color_scheme: dark

back_to_top: true
back_to_top_text: "ğŸ”"

footer_content: "Copyright &copy; 2024 Filip Å Ä‡ekiÄ‡. Distributed by an <a href=\"https://github.com/fscek/moj-zet-app-guide/blob/main/LICENSE\">MIT license.</a>"